# Site settings
title: CrunchSlashDev
description: 'Neat Things, Built Openly'
url: 'http://crunchslashdev.com'
baseurl: '/'
# google_analytics: 'UA-38179399-2'
piwik: '//crunchslashdev.com/piwik/'
disqus_shortname: 'crunchslashdev'

author:
  name: 'Randy Butts'
  email: admin@crunchslashdev.com
  twitter_username: crunchslashdev
  facebook_username: crunchslashdev

collections:
    - projects

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

ftp_host: 'ftp.crunchslashdev.com'
ftp_dir: '/home1/zacdakec/public_html/crunchslashdev'
ftp_passive: false

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
